### PR TITLE
Fix getting redirect URL from curl

### LINKED ISSUE #176: Doesn't connect any more.
Hi, as I suspect you may know, lgogdownloader no longer works. On my version (3.7 64 bit Arch) you get a "URL using bad/illegal format or missing URL" after entering the password. 

I notice the (removed forty curse words seven of which are illegal) stupid pictorial captcha is back again and I suspect this is something to do with it, though I did try building it with QT installed and it didn't seem to help. I did try it on Ubuntu from a USB key and that didn't work either (the Ubuntu one has it built in).

### PR DESCRIPTION
**Pull request by jetomit**
The `char*` set by `curl_easy_getinfo` may not be valid after the next `curl_easy_perform`, so copy it to a `std::string` instead. Fixes #176.

### CODE REVIEW

File: src/website.cpp [hunk 1]
```diff
@@ -250,6 +250,12 @@ std::vector<gameItem> Website::getGames()
     return games;
 }
 
+static std::string getCurlInfoString(CURL* handle, CURLINFO info)
+{
+    char* str;
+    return (curl_easy_getinfo(handle, info, &str) == CURLE_OK) ? str : "";
+}
+
```
Comment (Sude-) [inline src/website.cpp:258]: This helper function should be added to Util namespace and not be a static member of Website class

Comment (Sude-) [reply src/website.cpp:258]: Oops, it actually isn't part of the website class but just a static function.
Still it should probably be added to Util namespace like the other curl helper functions.

Comment (jetomit) [reply src/website.cpp:258]: I thought about that and put it near the `Website::Login` function since it is only used there. But the Util class also makes sense. I’ll update the PR.
